### ISSUE TITLE
std::logic_error

### ISSUE THREAD

**Issue by lguodongustc** [ros/nodelet_core#22]
I am new to ROS, when I run a nodelet as the tutorials, 
http://wiki.ros.org/nodelet/Tutorials/Running%20a%20nodelet
"rosrun nodelet nodelet manager __name:=nodelet_manager"  the terminal show 

"
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
Aborted (core dumped)
"
I have searched the answer about "std::logic_error" , it seems about Null pointer invalid use. 
could you please tell me how to solve it ?

My system environment is ROS+hydro+Ubuntu 12.04

**Comment by esteve** [comment]
I can't seem to reproduce this issue. Did you run anything else before starting the nodelet manager? Is roscore running?

**Comment by mxsrc** [comment]
I am experiencing this behavior, too. I can't pinpoint it right now, it happens when running my usual launch-file with three nodelets and a nodelet_manager. When starting the manager and the nodelets separatly the error does not occur though this might be due to parameters not being set up which usually come from my launchfile.
The exact error message is:

    terminate called after throwing an instance of 'std::logic_error'
    what(): basic_string::_M_construct null not valid

I will try to compile a debug version of the nodelet package and debug this issue.

I'm running kinetic on an up-to-date Archlinux.

Edit: It appears to be a bug in the Nodelet I am running on the manager. I would've thought the nodelet-manager catches such exceptions to keep other nodelets from also failing.
